apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-action
  name: nginx-action
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-action
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-action
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
