---

- hosts: all
  become: true

  tasks:

  - name: Install apache2,php latest and update repo on Ubuntu
    package:
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes